version: 2.1

orbs:
  newhighsco: newhighsco/orb@1.13.0

only-main: &only-main
  filters:
    branches:
      only:
        - main

workflows:
  version: 2
  test_and_release:
    jobs:
      - newhighsco/setup:
          name: setup
      - newhighsco/test:
          name: test
          requires:
            - setup
      - newhighsco/release:
          <<: *only-main
          name: release
          requires:
            - test
      - newhighsco/analyze:
          <<: *only-main
          name: analyze
          disable: true
          requires:
            - release
